# Generated by Django 4.2.16 on 2026-07-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='Se usará en la URL: /t/slug/', unique=True, verbose_name='Identificador único'),
        ),
    ]
