# Generated by Django 4.2.16 on 2026-04-28 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del lugar')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del lugar')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden en listas')),
            ],
            options={
                'verbose_name': 'Lugar de consulta',
                'verbose_name_plural': 'Lugares de consulta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la cita')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='programada', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio enviado')),
                ('recordatorio_fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('recordatorio_canal', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('ambos', 'WhatsApp y Email')], max_length=10, verbose_name='Canal usado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='agenda.lugarconsulta', verbose_name='Lugar de consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
