# Generated by Django 4.2.16 on 2026-07-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='tenant.tenant', verbose_name='Consultorio'),
        ),
        migrations.AddField(
            model_name='lugarconsulta',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='tenant.tenant', verbose_name='Consultorio'),
        ),
    ]
