# Generated by Django 4.2.16 on 2026-07-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('agenda', '0002_cita_tenant_lugarconsulta_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='citas', to='servicios.servicio', verbose_name='Servicios esperados'),
        ),
    ]
