# Generated by Django 4.2.16 on 2026-07-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_cita_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo de la cita'),
        ),
    ]
