# Generated by Django 4.2.16 on 2026-08-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_cita_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarconsulta',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
    ]
