# Generated by Django 4.2.16 on 2026-08-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_add_ciudad_to_lugarconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
    ]
