# Generated by Django 4.2.16 on 2026-04-28 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cedula', models.CharField(help_text='Formato: V-12345678 o E-12345678', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener formato V-xxxxxxxx o E-xxxxxxxx', regex='^[VvEe]-\\d{6,9}$')], verbose_name='Cédula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Opcional — se usará para recordatorios por correo', max_length=254, verbose_name='Email')),
                ('estado_civil', models.CharField(choices=[('soltera', 'Soltera'), ('casada', 'Casada'), ('union_libre', 'Unión libre'), ('divorciada', 'Divorciada'), ('viuda', 'Viuda')], max_length=20, verbose_name='Estado civil')),
                ('nivel_instruccion', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=20, verbose_name='Nivel de instrucción')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=200, verbose_name='Contacto de emergencia')),
                ('seguro_medico', models.CharField(blank=True, max_length=100, verbose_name='Seguro médico')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('enfermedades_cronicas', models.TextField(blank=True, verbose_name='Enfermedades crónicas')),
                ('cirugias_previas', models.TextField(blank=True, verbose_name='Cirugías previas')),
                ('medicacion_actual', models.TextField(blank=True, verbose_name='Medicación actual')),
                ('tabaquismo', models.BooleanField(default=False, verbose_name='Tabaquismo')),
                ('alcoholismo', models.BooleanField(default=False, verbose_name='Alcoholismo')),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Grupo sanguíneo')),
                ('transfusiones', models.BooleanField(default=False, verbose_name='Transfusiones')),
                ('antec_cancer_mama', models.BooleanField(default=False, verbose_name='Antec. familiar cáncer de mama')),
                ('antec_cancer_cuello', models.BooleanField(default=False, verbose_name='Antec. familiar cáncer de cuello uterino')),
                ('antec_diabetes', models.BooleanField(default=False, verbose_name='Antec. familiar diabetes')),
                ('antec_hipertension', models.BooleanField(default=False, verbose_name='Antec. familiar hipertensión')),
                ('antec_autoinmunes', models.TextField(blank=True, verbose_name='Antec. familiar enfermedades autoinmunes')),
                ('antec_geneticas', models.TextField(blank=True, verbose_name='Antec. familiar enfermedades genéticas')),
                ('menarquia', models.IntegerField(blank=True, null=True, verbose_name='Menarquía (edad)')),
                ('ciclo_dias', models.IntegerField(blank=True, null=True, verbose_name='Duración del ciclo (días)')),
                ('ciclo_regular', models.BooleanField(default=True, verbose_name='Ciclo regular')),
                ('fur', models.DateField(blank=True, null=True, verbose_name='FUR (Fecha última regla)')),
                ('gestas', models.IntegerField(default=0, verbose_name='Gestas')),
                ('partos', models.IntegerField(default=0, verbose_name='Partos')),
                ('cesareas', models.IntegerField(default=0, verbose_name='Cesáreas')),
                ('abortos', models.IntegerField(default=0, verbose_name='Abortos')),
                ('fecha_ultimo_parto', models.DateField(blank=True, null=True, verbose_name='Fecha último parto')),
                ('ultima_citologia_fecha', models.DateField(blank=True, null=True, verbose_name='Última citología (fecha)')),
                ('ultima_citologia_resultado', models.CharField(blank=True, max_length=100, verbose_name='Última citología (resultado)')),
                ('vph_diagnostico', models.BooleanField(default=False, verbose_name='Diagnóstico VPH')),
                ('vph_vacuna', models.BooleanField(default=False, verbose_name='Vacuna VPH')),
                ('vih_resultado', models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo'), ('no_realizado', 'No realizado')], default='no_realizado', max_length=20, verbose_name='Resultado VIH')),
                ('vih_fecha', models.DateField(blank=True, null=True, verbose_name='VIH (fecha prueba)')),
                ('its_previas', models.TextField(blank=True, verbose_name='ITS previas')),
                ('inicio_vida_sexual', models.IntegerField(blank=True, null=True, verbose_name='Inicio vida sexual (edad)')),
                ('num_parejas', models.IntegerField(blank=True, null=True, verbose_name='Número de parejas sexuales')),
                ('dispareunia', models.BooleanField(default=False, verbose_name='Dispareunia')),
                ('menopausia', models.BooleanField(default=False, verbose_name='Menopausia')),
                ('menopausia_edad', models.IntegerField(blank=True, null=True, verbose_name='Menopausia (edad)')),
                ('menopausia_sintomas', models.TextField(blank=True, verbose_name='Síntomas de menopausia')),
                ('metodo_anticonceptivo', models.CharField(blank=True, max_length=100, verbose_name='Método anticonceptivo actual')),
                ('metodo_tiempo_uso', models.CharField(blank=True, max_length=100, verbose_name='Tiempo de uso del método')),
                ('metodos_anteriores', models.TextField(blank=True, verbose_name='Métodos anticonceptivos anteriores')),
                ('deseo_embarazo', models.BooleanField(default=False, verbose_name='Deseo de embarazo')),
                ('diu_fecha', models.DateField(blank=True, null=True, verbose_name='DIU (fecha de colocación)')),
                ('diu_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de DIU')),
                ('ligadura', models.BooleanField(default=False, verbose_name='Ligadura de trompas')),
                ('observaciones', models.TextField(blank=True, help_text='Cualquier dato relevante adicional de la paciente', verbose_name='Observaciones generales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
