# Generated by Django 4.2.16 on 2026-07-25 22:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='tenant.tenant', verbose_name='Consultorio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(help_text='Formato: V-12345678 o E-12345678', max_length=15, validators=[django.core.validators.RegexValidator(message='La cédula debe tener formato V-xxxxxxxx o E-xxxxxxxx', regex='^[VvEe]-\\d{6,9}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones generales'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('tenant', 'cedula')},
        ),
    ]
