# Generated by Django 4.2.16 on 2026-07-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_tenant_alter_paciente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltera', 'Soltera'), ('casada', 'Casada'), ('union_libre', 'Unión libre'), ('divorciada', 'Divorciada'), ('viuda', 'Viuda')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nivel_instruccion',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=20, verbose_name='Nivel de instrucción'),
        ),
    ]
