# Generated by Django 4.2.16 on 2026-08-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antec_otros',
            field=models.TextField(blank=True, verbose_name='Otros antecedentes familiares'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ultima_citologia_hace',
            field=models.CharField(blank=True, help_text='Ej: "hace 2 años", "hace 6 meses"', max_length=100, verbose_name='Última citología (tiempo aproximado)'),
        ),
    ]
