# Generated by Django 4.2.16 on 2026-08-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_antec_otros_paciente_ultima_citologia_hace'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ciclo_caracteristicas',
            field=models.TextField(blank=True, verbose_name='Características del sangrado menstrual'),
        ),
    ]
