# Generated by Django 4.2.16 on 2026-08-20 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_datos_pai_venezuela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='ciclo_caracteristicas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ultima_citologia_hace',
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso_nacer',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='En gramos. Ej: 3200', max_digits=4, null=True, verbose_name='Peso al nacer (g)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='talla_nacer',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='En centímetros. Ej: 50.5', max_digits=4, null=True, verbose_name='Talla al nacer (cm)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antec_parto',
            field=models.TextField(blank=True, help_text='Vía de parto, edad gestacional, APGAR', verbose_name='Antecedentes del parto / nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula_representante',
            field=models.CharField(blank=True, help_text='Formato: V-12345678-1', max_length=20, validators=[django.core.validators.RegexValidator(message='La cédula del representante debe tener formato V-xxxxxxxx-N (ej: V-12345678-1)', regex='^[VvEe]-\\d{6,9}-\\d+$')], verbose_name='Cédula del representante'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cirugias_previas',
            field=models.TextField(blank=True, verbose_name='Cirugías y hospitalizaciones previas'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
