# Generated by Django 4.2.16 on 2026-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_remove_paciente_ciclo_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antec_alimentacion',
            field=models.TextField(blank=True, help_text='Lactancia materna/fórmula, ablactación, dieta actual, alergias alimentarias', verbose_name='Antecedentes de alimentación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antec_desarrollo',
            field=models.TextField(blank=True, help_text='Hitos del desarrollo: sostén cefálico, sedestación, marcha, lenguaje, control de esfínteres', verbose_name='Desarrollo psicomotor'),
        ),
    ]
