# Generated by Django 4.2.16 on 2026-09-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
        ('pacientes', '0018_pesquisa_pesquisarealizada'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pesquisarealizada',
            name='unique_paciente_pesquisa',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null = pesquisa estándar compartida.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas_extra', to='tenant.tenant', verbose_name='Consultorio'),
        ),
        migrations.AlterUniqueTogether(
            name='pesquisarealizada',
            unique_together={('paciente', 'pesquisa')},
        ),
    ]
