# Generated by Django 4.2.16 on 2026-07-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=200, verbose_name='Nombre del médico')),
                ('especialidad', models.CharField(blank=True, max_length=200, verbose_name='Especialidad')),
                ('logo_public_id', models.CharField(blank=True, max_length=500, verbose_name='Logo (Cloudinary public_id)')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email visible')),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Formato internacional sin +: 584121234567', max_length=20, verbose_name='Número WhatsApp')),
                ('whatsapp_mensaje', models.TextField(blank=True, help_text='Texto que se pre-carga al abrir WhatsApp desde la app', verbose_name='Mensaje por defecto WhatsApp')),
                ('color_primario', models.CharField(default='#2AACA8', help_text='Código hex: #2AACA8', max_length=7, verbose_name='Color primario')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenant.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuración del consultorio',
                'verbose_name_plural': 'Configuraciones de consultorios',
            },
        ),
    ]
