# Generated by Django 4.2.16 on 2026-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configconsultorio',
            name='nombre_consultorio',
            field=models.CharField(blank=True, help_text='Ej: Consultorio Ginecológico Santa María', max_length=200, verbose_name='Nombre del consultorio'),
        ),
        migrations.AlterField(
            model_name='configconsultorio',
            name='nombre_medico',
            field=models.CharField(blank=True, help_text='Ej: Dra. Vanessa Pereira', max_length=200, verbose_name='Nombre del médico'),
        ),
    ]
