# Generated by Django 4.2.16 on 2026-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configconsultorio_nombre_consultorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configconsultorio',
            name='color_sidebar',
            field=models.CharField(default='#1e1b2e', help_text='Fondo del menú lateral', max_length=7, verbose_name='Color de la barra lateral'),
        ),
        migrations.AlterField(
            model_name='configconsultorio',
            name='color_primario',
            field=models.CharField(default='#2AACA8', help_text='Color de botones y acentos', max_length=7, verbose_name='Color primario'),
        ),
        migrations.AlterField(
            model_name='configconsultorio',
            name='nombre_consultorio',
            field=models.CharField(blank=True, help_text='Ej: Consultorio Pediátrico Santa María', max_length=200, verbose_name='Nombre del consultorio'),
        ),
        migrations.AlterField(
            model_name='configconsultorio',
            name='nombre_medico',
            field=models.CharField(blank=True, help_text='Ej: Dr. Carlos Pérez', max_length=200, verbose_name='Nombre del médico'),
        ),
    ]
