# Generated by Django 4.2.16 on 2026-08-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configconsultorio_color_sidebar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configconsultorio',
            name='membrete_public_id',
            field=models.CharField(blank=True, help_text='Imagen banner horizontal para el récipe médico. Si se carga, reemplaza el membrete generado automáticamente.', max_length=500, verbose_name='Membrete récipe (Cloudinary public_id)'),
        ),
    ]
