# Generated by Django 4.2.16 on 2026-08-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configconsultorio_membrete_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configconsultorio',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='configconsultorio',
            name='nombre_medico',
        ),
    ]
