# Generated by Django 4.2.16 on 2026-09-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_remove_configconsultorio_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configconsultorio',
            name='duracion_cita_minutos',
            field=models.PositiveSmallIntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '1 hora'), (75, '1 h 15 min'), (90, '1 h 30 min'), (120, '2 horas')], default=30, verbose_name='Duración predeterminada de cita'),
        ),
        migrations.AddField(
            model_name='configconsultorio',
            name='horario_fin',
            field=models.TimeField(blank=True, help_text='Hora de cierre del consultorio (ej: 18:00)', null=True, verbose_name='Fin de jornada'),
        ),
        migrations.AddField(
            model_name='configconsultorio',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='Hora de apertura del consultorio (ej: 07:00)', null=True, verbose_name='Inicio de jornada'),
        ),
    ]
