# Generated by Django 4.2.16 on 2026-07-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('asistente', 'Asistente')], default='asistente', max_length=20, verbose_name='Rol'),
        ),
    ]
