# Generated by Django 4.2.16 on 2026-08-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_sexo_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='credenciales',
            field=models.CharField(blank=True, help_text='Ej: Especialista en Pediatría. Universidad Central de Venezuela', max_length=300, verbose_name='Credenciales / Posgrado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Ej: Pediatría y Puericultura', max_length=200, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_mpps',
            field=models.CharField(blank=True, help_text='Número de registro médico profesional', max_length=50, verbose_name='Número MPPS / CMP'),
        ),
    ]
