# Generated by Django 4.2.16 on 2026-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_credenciales_usuario_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del médico', max_length=30, verbose_name='Teléfono'),
        ),
    ]
