# Generated by Django 4.2.16 on 2026-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuario_firma_sello_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner_public_id',
            field=models.CharField(blank=True, help_text='Imagen de encabezado que sustituye el membrete en los PDFs cuando está habilitado.', max_length=500, verbose_name='Banner PDF (Cloudinary public_id)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usar_banner',
            field=models.BooleanField(default=False, help_text='Si está marcado, los PDFs mostrarán el banner en lugar del membrete estándar.', verbose_name='Usar banner en PDFs'),
        ),
    ]
