# Generated by Django 4.2.16 on 2026-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolicitudIdempotente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("usuario_id", models.IntegerField(blank=True, null=True)),
                ("ruta", models.CharField(max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[("procesando", "Procesando"), ("ok", "Completada")],
                        default="procesando",
                        max_length=12,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=500)),
                ("creado", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Solicitud idempotente",
                "verbose_name_plural": "Solicitudes idempotentes",
            },
        ),
    ]
