# Generated by Django 4.2.16 on 2026-04-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de consulta')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('sintomas_actuales', models.TextField(blank=True, verbose_name='Síntomas actuales')),
                ('examen_fisico', models.TextField(blank=True, verbose_name='Examen físico')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima cita')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('tension_arterial', models.CharField(blank=True, help_text='Ej: 120/80', max_length=20, verbose_name='Tensión arterial')),
                ('es_prenatal', models.BooleanField(default=False, verbose_name='Es control prenatal')),
                ('fpp', models.DateField(blank=True, null=True, verbose_name='FPP (Fecha probable de parto)')),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True, verbose_name='Semanas de gestación')),
                ('altura_uterina', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Altura uterina (cm)')),
                ('fcf', models.IntegerField(blank=True, null=True, verbose_name='FCF (Frecuencia cardíaca fetal, lpm)')),
                ('presentacion_fetal', models.CharField(blank=True, max_length=50, verbose_name='Presentación fetal')),
                ('edemas', models.BooleanField(blank=True, null=True, verbose_name='Edemas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='agenda.cita', verbose_name='Cita asociada')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='agenda.lugarconsulta', verbose_name='Lugar de consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=100, verbose_name='ID de archivo en Drive')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('pdf', 'PDF')], max_length=10, verbose_name='Tipo')),
                ('drive_folder_id', models.CharField(blank=True, max_length=100, verbose_name='ID de carpeta en Drive')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='consultas.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['subido_en'],
            },
        ),
    ]
