# Generated by Django 4.2.16 on 2026-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='laboratorio',
            field=models.TextField(blank=True, help_text='Valores de exámenes de laboratorio', verbose_name='Laboratorio'),
        ),
    ]
