# Generated by Django 4.2.16 on 2026-05-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntoconsulta',
            name='drive_file_id',
            field=models.CharField(max_length=500, verbose_name='ID de archivo en Drive'),
        ),
    ]
