# Generated by Django 4.2.16 on 2026-07-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
        ('consultas', '0003_alter_adjuntoconsulta_drive_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='tenant.tenant', verbose_name='Consultorio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='laboratorio',
            field=models.TextField(blank=True, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tension_arterial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tensión arterial'),
        ),
    ]
