# Generated by Django 4.2.16 on 2026-07-29 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0004_consulta_tenant_alter_consulta_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_pago',
            field=models.CharField(blank=True, max_length=200, verbose_name='Notas de pago'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(blank=True, verbose_name='Motivo / notas adicionales'),
        ),
        migrations.CreateModel(
            name='ConsultaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio USD al momento')),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tasa al momento')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_usados', to='consultas.consulta')),
            ],
            options={
                'verbose_name': 'Servicio de consulta',
                'verbose_name_plural': 'Servicios de consulta',
            },
        ),
    ]
