# Generated by Django 4.2.16 on 2026-07-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('consultas', '0005_consulta_medico_consulta_notas_pago_consulta_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='servicios.servicio'),
        ),
    ]
