# Generated by Django 4.2.16 on 2026-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_consultaservicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='colposcopia',
            field=models.TextField(blank=True, verbose_name='Colposcopia'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='ecografia',
            field=models.TextField(blank=True, verbose_name='Ecografía'),
        ),
    ]
