# Generated by Django 4.2.16 on 2026-08-03 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
        ('servicios', '0001_initial'),
        ('agenda', '0004_alter_cita_motivo'),
        ('pacientes', '0003_alter_paciente_estado_civil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0007_consulta_colposcopia_consulta_ecografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pagado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimiento', to='agenda.cita')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='pacientes.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos', to='servicios.servicio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
