# Generated by Django 4.2.16 on 2026-08-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_consulta_pediatrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='apetito',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo / hiporexia')], max_length=10, verbose_name='Apetito'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='consistencia_deposiciones',
            field=models.CharField(blank=True, choices=[('normal', 'Normal / pastosa'), ('blanda', 'Blanda / semilíquida'), ('liquida', 'Líquida / diarrea'), ('dura', 'Dura / caprinas')], max_length=10, verbose_name='Consistencia de deposiciones'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='control_esfinteres',
            field=models.BooleanField(blank=True, null=True, verbose_name='Control de esfínteres logrado'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='duracion_siesta',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duración de siesta (min)'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuencia_deposiciones',
            field=models.CharField(blank=True, choices=[('varias_dia', 'Varias veces al día'), ('una_dia', 'Una vez al día'), ('cada_2_3', 'Cada 2-3 días'), ('estreñimiento', 'Estreñimiento (>3 días)')], max_length=15, verbose_name='Frecuencia de deposiciones'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='horas_sueno_nocturno',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas de sueño nocturno'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_alimentacion',
            field=models.TextField(blank=True, help_text='Alimentos rechazados, alergias alimentarias, hábitos especiales', verbose_name='Notas de alimentación'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_eliminacion',
            field=models.TextField(blank=True, help_text='Hematuria, disuria, enuresis, encopresis', verbose_name='Notas de eliminación'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_sueno',
            field=models.TextField(blank=True, help_text='Ronquidos, despertares frecuentes, pesadillas, comparte cama', verbose_name='Notas de sueño'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='num_comidas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de comidas al día'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='num_siestas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de siestas al día'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_alimentacion',
            field=models.CharField(blank=True, choices=[('lme', 'Lactancia materna exclusiva'), ('mixta', 'Lactancia mixta'), ('formula', 'Fórmula exclusiva'), ('complementaria', 'Alimentación complementaria + lactancia'), ('familiar', 'Dieta familiar')], max_length=20, verbose_name='Tipo de alimentación'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sintomas_actuales',
            field=models.TextField(blank=True, verbose_name='Enfermedad actual / síntomas'),
        ),
    ]
