# Generated by Django 4.2.16 on 2026-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0011_consulta_apetito_consulta_consistencia_deposiciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='indicaciones',
            field=models.TextField(blank=True, help_text='Instrucciones específicas para el paciente o representante', verbose_name='Indicaciones'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(blank=True, verbose_name='Tratamiento / Plan'),
        ),
    ]
