# Generated by Django 4.2.16 on 2026-08-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
        ('consultas', '0013_consultaservicio_costo_adquisicion_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('indicaciones', models.TextField(help_text='Ej: 1 tableta cada 8 horas por 5 días', verbose_name='Indicaciones por defecto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='tenant.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
