# Generated by Django 4.2.16 on 2026-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0018_medicamento_unidad_dosis_kg_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='concentracion_mg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='mg del principio activo en la unidad de medida base. Solo para unidades de masa.', max_digits=8, null=True, verbose_name='Concentración (mg)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis_fija',
            field=models.CharField(blank=True, help_text='Ej: 2 puffs, 1 inhalación, 1 sobre. Se usa como {{DOSIS}} sin calcular por kg.', max_length=50, verbose_name='Dosis fija'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis_max_absoluta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Techo del adulto. Solo aplica a unidades de masa. La dosis calculada nunca superará este valor.', max_digits=8, null=True, verbose_name='Dosis máxima absoluta (mg/dosis)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis_mg_kg_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Completar solo si hay rango (leve / severo). Dejar vacío para dosis fija.', max_digits=7, null=True, verbose_name='Dosis máxima (por kg/dosis)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis_mg_kg_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Si no hay rango, usar solo este campo como dosis fija.', max_digits=7, null=True, verbose_name='Dosis mínima (por kg/dosis)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='duracion_dias',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de días del tratamiento.', null=True, verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='edad_max_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Alerta si el paciente supera esta edad (revisar dosis adulto).', null=True, verbose_name='Edad máxima (meses)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='edad_min_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Se mostrará advertencia si el paciente es menor de esta edad.', null=True, verbose_name='Edad mínima (meses)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='frecuencia_horas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cada cuántas horas se administra. Ej: 8 → cada 8 horas.', null=True, verbose_name='Frecuencia (horas)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='peso_min_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advertencia si el paciente pesa menos de este valor.', max_digits=5, null=True, verbose_name='Peso mínimo (kg)'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='unidad_resultado',
            field=models.CharField(blank=True, choices=[('mL', 'mL (jarabe / gotas)'), ('tableta', 'Tableta / cápsula'), ('mg', 'mg directo'), ('UI', 'Unidades internacionales'), ('gotas', 'Gotas'), ('puff', 'Puff / inhalación'), ('aplicacion', 'Aplicación'), ('sobre', 'Sobre')], help_text='Solo para unidades de masa (mg/kg, mcg/kg, UI/kg).', max_length=10, verbose_name='Unidad del resultado'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='volumen_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mL correspondientes a la concentración indicada. Ej: 5 para "250 mg/5 mL". Dejar vacío para tabletas.', max_digits=6, null=True, verbose_name='Volumen base (mL)'),
        ),
    ]
