# Generated by Django 4.2.16 on 2026-09-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0022_remove_procedimiento_campos_viejos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaservicio',
            name='descuento_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se resta del precio del servicio. No aplica si está exonerado.', max_digits=8, verbose_name='Descuento (USD)'),
        ),
        migrations.AlterField(
            model_name='consultaservicio',
            name='exonerado',
            field=models.BooleanField(default=False, help_text='No se cobra este servicio, pero queda registrado.', verbose_name='Exonerado'),
        ),
        migrations.AlterField(
            model_name='procedimientoservicio',
            name='descuento_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se resta del precio del servicio. No aplica si está exonerado.', max_digits=8, verbose_name='Descuento (USD)'),
        ),
        migrations.AlterField(
            model_name='procedimientoservicio',
            name='exonerado',
            field=models.BooleanField(default=False, help_text='No se cobra este servicio, pero queda registrado.', verbose_name='Exonerado'),
        ),
    ]
